language: rust

rust:
  - nightly-2019-11-06

cache: cargo

before_script:
  - rustup component add clippy rustfmt

script: |
  cargo fmt --all -- --check &&
  cargo clippy -- -D warnings &&
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

branches:
  only:
    - staging # bors r+
    - trying  # bors try
    - master
