[workspace]
members = [
    "eth2/types",
    "eth2/utils/int_to_bytes",
    "eth2/utils/ssz_types",
    "eth2/simulation",
    "eth2/simulation_args",
    'simulation_server',
    'simulation_client',
    'simulation_client_example',
]
