[package]
name = "notion-server"
version = "0.1.0"
authors = [
    "Ansgar Dietrichs <ansgar.dietrichs@consensys.net>",
    "Greg Trowbridge <gregory.trowbridge@consensys.net>",
    "Sam Wilson <sam.wilson@consensys.net>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
rocket = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.6.0"
structopt = "0.3.4"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin/server.rs"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]